const DEFAULT_SERVER_URL = "https://kuisdharmaapi.herokuapp.com";

const CARD_ELEVATION = 10.0;

const DEFAULT_TIMER_PER_QUESTION_IN_SECONDS = 60;
const DEFINITION_TIME_PER_QUESTION_IN_SECONDS = "TIME_PER_QUESTION_IN_SECONDS";